
function Footer(props) {
    return(
        <div className='page-footer'>
            <div className="page-container">
                <div className="desktop-footer">
                    <div className="company-info">
                        MATKA 365 is a limited liability company incorporated under the laws of Curacao Players are requested not to contact any untrusted sources for MATKA 365 
                        accounts as this is an online site and they can only register independently without any agents. Only deposit through the account details generated by the system
                        or provided by our official support team.
                    </div>
                    <div className="companies-logo">
                        <div className="item">
                            <img src='images/user/companies-icons/mga.png'/>
                        </div>
                        <div className="item">
                            <img src='images/user/companies-icons/begamble.png'/>
                        </div>
                        <div className="item">
                            <img src='images/user/companies-icons/bank.png'/>
                        </div>
                        <div className="item">
                            <img src='images/user/companies-icons/ecogra.png'/>
                        </div>
                        <div className="item">
                            <img src='images/user/companies-icons/gambling.png'/>
                        </div>
                    </div>
                    <div className="policy-group">
                        <div className="item">
                            RULES AND REGULATIONS
                        </div>
                        <div className="item">
                            TERMS & CONDITIONS  
                        </div>
                        <div className="item">
                            PRIVACY POLICIES
                        </div>
                        <div className="item">
                            RESPONSIBLE GAMBLING
                        </div>
                    </div>
                    <div className="version">
                        MATKA365 NC. ALL RIGHTS RESERVED V2.0.1
                    </div>
                </div>
            </div>
        </div>
    ) ;
}
export default Footer ;